version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 879772956301.dkr.ecr.us-west-1.amazonaws.com
      - REPOSITORY_URI=879772956301.dkr.ecr.us-west-1.amazonaws.com/user162-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd frontend
      - echo "Frontend Build started on `date`"
      - echo "Installing NPM dependencies..."
      - npm install
      - echo "Setting environment variables..."
      - export VITE_API_BASE_URL="http://a4ac720e9ab444c55b13081326853612-1170809007.us-west-1.elb.amazonaws.com" # 이 부분을 실제 백엔드 서비스의 ELB 주소로 반드시 교체해야 합니다.
      - echo "Building the React app..."
      - npm run build
      
      - echo "Creating Dockerfile..."
      - echo "FROM nginx:alpine" > Dockerfile
      - echo "COPY dist /usr/share/nginx/html" >> Dockerfile
      - echo "EXPOSE 80" >> Dockerfile
      - echo "CMD [\"nginx\", \"-g\", \"daemon off;\"]" >> Dockerfile
      
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG