version: 0.2

phases:
  pre_build:
    commands:
      # frontend 폴더로 이동 후 패키지 설치
      - cd frontend
      - echo "Installing NPM dependencies..."
      - npm install
  build:
    commands:
      - echo "Setting environment variables..."
      - export VITE_API_BASE_URL="http://a4ac720e9ab444c55b13081326853612-1170809007.us-west-1.elb.amazonaws.com"
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed."
      
artifacts:
  # 빌드 결과물 경로도 frontend 하위의 dist 폴더로 변경
  base-directory: frontend/dist
  files:
    - '**/*'