apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookapp-frontend
  template:
    metadata:
      labels:
        app: bookapp-frontend
    spec:
      containers:
      - name: bookapp-frontend
        # 💡 [중요] 방금 만든 프론트엔드 ECR URI로 변경하세요!
        image: <본인의_AWS_계정ID>[.dkr.ecr.us-west-1.amazonaws.com/user162-frontend:latest](https://.dkr.ecr.us-west-1.amazonaws.com/user162-frontend:latest)
        ports:
        - containerPort: 80 # Nginx 기본 포트
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-frontend-svc
spec:
  type: LoadBalancer # 사용자가 접속할 최종 웹사이트 주소를 만들어줍니다.
  selector:
    app: bookapp-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80